name: CI Pipe

on:
  push:
    branches: ["master"]


jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t sachith

      - name: Run compose
        run: docker compose up

      - name: Run tests
        run: docker ps
        run: "Tests ran successfully"

